name: Build README

on:
  push:
  workflow_dispatch:

  # once per day
  schedule:
    - cron:  '42 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Make README
      env:
        TWITTER_API_KEY            : ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY     : ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN       : ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |-
        python make_readme.py -y

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Updated README

        # Optional glob pattern of files which should be added to the commit
        file_pattern: README.md

        # Optional commit user and author settings
        commit_user_name : GitHub Actions Bot
        commit_user_email: github-actions-bot@example.org
        commit_author    : GitHub Actions Bot <actions@github.com>
